name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Render
        uses: render-deploy-action@v1.0.0
        with:
          render_email: ${{ secrets.RENDER_EMAIL }}
          render_api_key: ${{ secrets.RENDER_API_KEY }}
          render_service_name: ${{ secrets.RENDER_SERVICE_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
